year= input("Write a year: ")
adjective = input("Write an adjective (descriptive word): ")
place = input("Write the name of a place: ")
name = input("Write the name of a character: ")
adjective2 = input("Write a second adjective (descriptive word): ")
color= input("Write a color: ")
number= input("Write a number: ")
noun = input("Write a noun (thing) in plural: ")
adjective3 = input("Write a third adjective (descriptive word): ")
creature= input("write the name of an imaginary creature: ")
exclamation= input("Write a swear: ")


print (f"In the year {year}, the galaxy was buzzing with excitement about the annual {adjective} Space Race.")
print(f"Pilots from all over the universe gathered at {place} to compete. The favorite to win was {name}, known for their {adjective2} piloting skills.")
print (f"As the race began, {name} quickly took the lead in their {color} spaceship. They zoomed past {number} {noun} and dodged {adjective3} asteroids.")
print(f"Suddenly, a {creature} appeared on the track, causing chaos.")
print(f"{exclamation}! shouted {name}, as they skillfully maneuvered around the {creature}.")
print(f"With a final burst of speed, they crossed the finish line and won the race. The crowd at {place} erupted in cheers, and {name} was awarded a {noun} as the grand prize.")